language: node_js
node_js:
  - "stable"
services:
  - postgresql
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
script:
  - npm run test